# Generated by Django 4.0.5 on 2022-07-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGal', '0005_delete_webprofile_userprofile_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='andalusia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brazil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='england',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nubia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portugal',
            field=models.BooleanField(default=False),
        ),
    ]
