# Generated by Django 4.0.5 on 2022-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGal', '0006_userprofile_andalusia_userprofile_brazil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='andalusia',
            field=models.BooleanField(default=False, verbose_name='andalusia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='brazil',
            field=models.BooleanField(default=False, verbose_name='brazil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='england',
            field=models.BooleanField(default=False, verbose_name='england'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nubia',
            field=models.BooleanField(default=False, verbose_name='nubia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portugal',
            field=models.BooleanField(default=False, verbose_name='portugal'),
        ),
    ]
