# Generated by Django 4.0.5 on 2022-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGal', '0007_alter_userprofile_andalusia_alter_userprofile_brazil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_points',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
