# Generated by Django 4.0.5 on 2022-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256)),
                ('profile_points', models.PositiveIntegerField(default=0, verbose_name='ship_coins')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_points',
        ),
    ]
