# Generated by Django 4.0.5 on 2022-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_webprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebProfile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
