# Generated by Django 4.0.5 on 2022-08-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='world_history_quiz',
            field=models.BooleanField(default=False, verbose_name='world_history_quiz'),
        ),
    ]
