# Generated by Django 4.0.5 on 2022-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_world_history_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='world_history_quiz',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_collection_1',
            field=models.BooleanField(default=False, verbose_name='img_collection_1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_collection_2',
            field=models.BooleanField(default=False, verbose_name='img_collection_2'),
        ),
    ]
