# Generated by Django 4.0.5 on 2022-08-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_world_history_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.CharField(choices=[('grey_robot', 'img/profile1.png'), ('purple_robot', 'img/profile2.png'), ('rainbow_robot', 'img/profile3.png')], default='grey_robot', max_length=100),
        ),
    ]
