# Generated by Django 4.0.5 on 2022-08-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.CharField(choices=[('Grey Robot', 'Grey Robot'), ('Purple Robot', 'Purple Robot'), ('Rainbow Robot', 'Rainbow Robot'), ('[(\'Grey Robot\', "{% static \'icons/profile1.png\'%}"), (\'Purple Robot\', "{% static \'icons/profile2.png\'%}"), (\'Rainbow Robot\', "{% static \'icons/profile3.png\'%}")]', 'Profile Image Choices')], default='Grey Robot', max_length=500),
        ),
    ]
