# Generated by Django 4.0.5 on 2022-08-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.CharField(choices=[("{% static 'icons/profile1.png'%}", 'Grey Robot'), ('Purple Robot', 'Purple Robot'), ('Rainbow Robot', 'Rainbow Robot'), ('[("{% static \'icons/profile1.png\'%}", "{% static \'icons/profile1.png\'%}"), (\'Purple Robot\', "{% static \'icons/profile2.png\'%}"), (\'Rainbow Robot\', "{% static \'icons/profile3.png\'%}")]', 'Profile Image Choices')], default="{% static 'icons/profile1.png'%}", max_length=500),
        ),
    ]
