# Generated by Django 4.0.5 on 2022-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(default='Description here', max_length=500),
        ),
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='points'),
        ),
    ]
